version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0

jobs:
  test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            pip install poetry
            poetry install
      - run:
          name: Run tests and collect coverage
          command: |
            poetry run coverage run -m pytest test/
            poetry run coverage xml
            poetry run pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - test
