version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run:
          name: Run tests and collect coverage
          command: |
            python -m coverage run -m pytest test/
            python -m coverage xml
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
